server:
  application:
    name: test
  port: 8080

spring:
  datasource:
#    mysql5.7
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: aa1016
    url: jdbc:mysql://localhost:3307/test?useSSL=false&serverTimezone=UTC
    username: root
    password: Aaa1016.
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher