server:
  application:
    name: test
  port: 8080

spring:
  datasource:
#    mysql5.7
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: aa1016
    url: jdbc:mysql://localhost:3307/test?useSSL=false&serverTimezone=UTC
    username: root
    password: Aaa1016.
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
      timeout: 1000ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher